import json
import os

nb_path = r'c:\Users\dani9\.gemini\antigravity\scratch\deep_learning_project\main_experiment.ipynb'

try:
    with open(nb_path, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    # Define the new source code for each experiment type
    # keys are unique substrings to identify the cell

    updates = {
        "Experiment: SVD": [
            "# --- CELL 5: Experiment 2 - Standard SVD ---\n",
            "print(\"\\n--- Experiment: SVD ---\")\n",
            "\n",
            "# 1. Reload Clean Weights\n",
            "model_current = get_resnet18(num_classes=10).to(DEVICE)\n",
            "model_current.load_state_dict(torch.load(\"checkpoints/task_a_expert.pth\"))\n",
            "\n",
            "# 2. Subspace Extraction\n",
            "projector = SVDProjector()\n",
            "start_time = time.time()\n",
            "projector.compute_subspaces(model_current)\n",
            "prep_time = time.time() - start_time\n",
            "print(f\"Subspace computed in {prep_time:.2f}s\")\n",
            "\n",
            "# --- NEW: Zero-Shot Eval ---\n",
            "acc_A_zero = evaluate(model_current, test_A, DEVICE, task_classes=[0, 1, 2, 3, 4])\n",
            "compression_damage = acc_A_initial - acc_A_zero\n",
            "print(f\"Zero-Shot A Accuracy: {acc_A_zero:.2f}% (Drop: {compression_damage:.2f}%)\")\n",
            "\n",
            "# 3. Constrained Training\n",
            "model_current = train_constrained(model_current, train_B, EPOCHS_B, DEVICE, projector)\n",
            "\n",
            "# 4. Metrics\n",
            "# FIX: Mask for Task A (0-4)\n",
            "acc_A_final = evaluate(model_current, test_A, DEVICE, task_classes=[0, 1, 2, 3, 4])\n",
            "# FIX: Mask for Task B (5-9)\n",
            "acc_B_final = evaluate(model_current, test_B, DEVICE, task_classes=[5, 6, 7, 8, 9])\n",
            "forgetting = acc_A_initial - acc_A_final\n",
            "\n",
            "results.append({\n",
            "    \"Method\": \"SVD\",\n",
            "    \"Task A Acc (Retention)\": acc_A_final,\n",
            "    \"Task B Acc (Plasticity)\": acc_B_final,\n",
            "    \"Forgetting\": forgetting,\n",
            "    \"Zero-Shot A\": acc_A_zero,\n",
            "    \"Compression Damage\": compression_damage,\n",
            "    \"Forgetting (Training)\": acc_A_zero - acc_A_final,\n",
            "    \"Prep Time (s)\": prep_time\n",
            "})\n",
            "print(f\"SVD Result: Initial A={acc_A_initial:.2f}%, Final B={acc_B_final:.2f}%, Final A={acc_A_final:.2f}%, Forgetting={forgetting:.2f}%, Prep Time={prep_time:.2f}s\")\n"
        ],
        "Experiment: Adaptive SVD": [
            "# --- CELL 6: Experiment 3 - Adaptive SVD ---\n",
            "print(\"\\n--- Experiment: Adaptive SVD ---\")\n",
            "\n",
            "# 1. Reload Clean Weights\n",
            "model_current = get_resnet18(num_classes=10).to(DEVICE)\n",
            "model_current.load_state_dict(torch.load(\"checkpoints/task_a_expert.pth\"))\n",
            "\n",
            "# 2. Subspace Extraction (Note: Uses Task A test set for importance)\n",
            "# We set mrr=0.4 (40% min retention) and trr=0.95 (95% max retention)\n",
            "projector = AdaptiveSVDProjector(mrr=0.4, trr=0.95)\n",
            "start_time = time.time()\n",
            "# Using test_A (Task A) loader to evaluate importance for RETAINING Task A\n",
            "projector.compute_subspaces(model_current, test_A, DEVICE)\n",
            "prep_time = time.time() - start_time\n",
            "print(f\"Subspace computed in {prep_time:.2f}s\")\n",
            "\n",
            "# --- NEW: Zero-Shot Eval ---\n",
            "acc_A_zero = evaluate(model_current, test_A, DEVICE, task_classes=[0, 1, 2, 3, 4])\n",
            "compression_damage = acc_A_initial - acc_A_zero\n",
            "print(f\"Zero-Shot A Accuracy: {acc_A_zero:.2f}% (Drop: {compression_damage:.2f}%)\")\n",
            "\n",
            "# 3. Constrained Training\n",
            "model_current = train_constrained(model_current, train_B, EPOCHS_B, DEVICE, projector)\n",
            "\n",
            "# 4. Metrics\n",
            "acc_A_final = evaluate(model_current, test_A, DEVICE, task_classes=[0, 1, 2, 3, 4])\n",
            "acc_B_final = evaluate(model_current, test_B, DEVICE, task_classes=[5, 6, 7, 8, 9])\n",
            "forgetting = acc_A_initial - acc_A_final\n",
            "\n",
            "results.append({\n",
            "    \"Method\": \"Adaptive SVD\",\n",
            "    \"Task A Acc (Retention)\": acc_A_final,\n",
            "    \"Task B Acc (Plasticity)\": acc_B_final,\n",
            "    \"Forgetting\": forgetting,\n",
            "    \"Zero-Shot A\": acc_A_zero,\n",
            "    \"Compression Damage\": compression_damage,\n",
            "    \"Forgetting (Training)\": acc_A_zero - acc_A_final,\n",
            "    \"Prep Time (s)\": prep_time\n",
            "})\n",
            "print(f\"Adaptive SVD Result: Initial A={acc_A_initial:.2f}%, Final B={acc_B_final:.2f}%, Final A={acc_A_final:.2f}%, Forgetting={forgetting:.2f}%, Prep Time={prep_time:.2f}s\")\n"
        ],
        "Experiment: Pivoted QR": [
            "# --- CELL 7: Experiment 4 - Pivoted QR Decomposition ---\n",
            "print(\"\\n--- Experiment: Pivoted QR Decomposition ---\")\n",
            "\n",
            "# 1. Reload Clean Weights\n",
            "model_current = get_resnet18(num_classes=10).to(DEVICE)\n",
            "model_current.load_state_dict(torch.load(\"checkpoints/task_a_expert.pth\"))\n",
            "\n",
            "# 2. Subspace Extraction\n",
            "# rank_fraction=0.5 ensures fair comparison with Standard SVD (50%)\n",
            "qr_projector = QRProjector(rank_fraction=0.5)\n",
            "start_time = time.time()\n",
            "qr_projector.compute_subspaces(model_current, device=DEVICE) # Data not needed for QR\n",
            "prep_time = time.time() - start_time\n",
            "print(f\"QR Subspace computed in {prep_time:.2f}s\")\n",
            "\n",
            "# --- NEW: Zero-Shot Eval ---\n",
            "acc_A_zero = evaluate(model_current, test_A, DEVICE, task_classes=[0, 1, 2, 3, 4])\n",
            "compression_damage = acc_A_initial - acc_A_zero\n",
            "print(f\"Zero-Shot A Accuracy: {acc_A_zero:.2f}% (Drop: {compression_damage:.2f}%)\")\n",
            "\n",
            "# 3. Constrained Training\n",
            "model_current = train_constrained(model_current, train_B, EPOCHS_B, DEVICE, qr_projector)\n",
            "\n",
            "# 4. Metrics\n",
            "acc_A_final = evaluate(model_current, test_A, DEVICE, task_classes=[0, 1, 2, 3, 4])\n",
            "acc_B_final = evaluate(model_current, test_B, DEVICE, task_classes=[5, 6, 7, 8, 9])\n",
            "forgetting = acc_A_initial - acc_A_final\n",
            "\n",
            "results.append({\n",
            "    \"Method\": \"Pivoted QR\",\n",
            "    \"Task A Acc (Retention)\": acc_A_final,\n",
            "    \"Task B Acc (Plasticity)\": acc_B_final,\n",
            "    \"Forgetting\": forgetting,\n",
            "    \"Zero-Shot A\": acc_A_zero,\n",
            "    \"Compression Damage\": compression_damage,\n",
            "    \"Forgetting (Training)\": acc_A_zero - acc_A_final,\n",
            "    \"Prep Time (s)\": prep_time\n",
            "})\n",
            "print(f\"Pivoted QR Result: Initial A={acc_A_initial:.2f}%, Final B={acc_B_final:.2f}%, Final A={acc_A_final:.2f}%, Forgetting={forgetting:.2f}%, Prep Time={prep_time:.2f}s\")\n"
        ],
        "Experiment: RSVD": [
            "# --- CELL 8: Experiment 5 - Randomized SVD ---\n",
            "print(\"\\n--- Experiment: RSVD ---\")\n",
            "\n",
            "# 1. Reload Clean Weights\n",
            "model_current = get_resnet18(num_classes=10).to(DEVICE)\n",
            "model_current.load_state_dict(torch.load(\"checkpoints/task_a_expert.pth\"))\n",
            "\n",
            "# 2. Subspace Extraction\n",
            "projector = RSVDProjector(rank_fraction=0.5, p=10, q=2)\n",
            "start_time = time.time()\n",
            "projector.compute_subspaces(model_current)\n",
            "prep_time = time.time() - start_time\n",
            "print(f\"Subspace computed in {prep_time:.2f}s\")\n",
            "\n",
            "# --- NEW: Zero-Shot Eval ---\n",
            "acc_A_zero = evaluate(model_current, test_A, DEVICE, task_classes=[0, 1, 2, 3, 4])\n",
            "compression_damage = acc_A_initial - acc_A_zero\n",
            "print(f\"Zero-Shot A Accuracy: {acc_A_zero:.2f}% (Drop: {compression_damage:.2f}%)\")\n",
            "\n",
            "# 3. Constrained Training\n",
            "model_current = train_constrained(model_current, train_B, EPOCHS_B, DEVICE, projector)\n",
            "\n",
            "# 4. Metrics\n",
            "acc_A_final = evaluate(model_current, test_A, DEVICE, task_classes=[0, 1, 2, 3, 4])\n",
            "acc_B_final = evaluate(model_current, test_B, DEVICE, task_classes=[5, 6, 7, 8, 9])\n",
            "forgetting = acc_A_initial - acc_A_final\n",
            "\n",
            "results.append({\n",
            "    \"Method\": \"RSVD\",\n",
            "    \"Task A Acc (Retention)\": acc_A_final,\n",
            "    \"Task B Acc (Plasticity)\": acc_B_final,\n",
            "    \"Forgetting\": forgetting,\n",
            "    \"Zero-Shot A\": acc_A_zero,\n",
            "    \"Compression Damage\": compression_damage,\n",
            "    \"Forgetting (Training)\": acc_A_zero - acc_A_final,\n",
            "    \"Prep Time (s)\": prep_time\n",
            "})\n",
            "print(f\"RSVD Result: Initial A={acc_A_initial:.2f}%, Final B={acc_B_final:.2f}%, Final A={acc_A_final:.2f}%, Forgetting={forgetting:.2f}%, Prep Time={prep_time:.2f}s\")\n"
        ],
        "Experiment: Global Magnitude Pruning": [
            "# --- CELL 9: Experiment 6 - Global Magnitude Pruning ---\n",
            "print(\"\\n--- Experiment: Global Magnitude Pruning ---\")\n",
            "\n",
            "sparsity_targets = [0.2, 0.4, 0.6]\n",
            "\n",
            "for sp in sparsity_targets:\n",
            "    print(f\"\\n>>> Testing Sparsity Target: {sp*100:.0f}%\")\n",
            "    \n",
            "    # 1. Reload Clean Weights\n",
            "    model_current = get_resnet18(num_classes=10).to(DEVICE)\n",
            "    model_current.load_state_dict(torch.load(\"checkpoints/task_a_expert.pth\"))\n",
            "    \n",
            "    # 2. Pruning (Subspace Extraction)\n",
            "    projector = MagnitudePruningProjector(sparsity_target=sp)\n",
            "    start_time = time.time()\n",
            "    projector.compute_subspaces(model_current)\n",
            "    prep_time = time.time() - start_time\n",
            "    \n",
            "    # 3. Zero-Shot Evaluation\n",
            "    acc_A_zero = evaluate(model_current, test_A, DEVICE, task_classes=[0, 1, 2, 3, 4])\n",
            "    compression_damage = acc_A_initial - acc_A_zero\n",
            "    print(f\"Zero-Shot: {acc_A_zero:.2f}% (Compression Damage: {compression_damage:.2f}%)\")\n",
            "    \n",
            "    # 4. Constrained Training\n",
            "    model_current = train_constrained(model_current, train_B, EPOCHS_B, DEVICE, projector)\n",
            "    \n",
            "    # 5. Metrics\n",
            "    acc_A_final = evaluate(model_current, test_A, DEVICE, task_classes=[0, 1, 2, 3, 4])\n",
            "    acc_B_final = evaluate(model_current, test_B, DEVICE, task_classes=[5, 6, 7, 8, 9])\n",
            "    forgetting = acc_A_initial - acc_A_final\n",
            "    \n",
            "    results.append({\n",
            "        \"Method\": f\"Pruning ({sp*100:.0f}%)\",\n",
            "        \"Sparsity\": sp,\n",
            "        \"Task A Acc (Retention)\": acc_A_final,\n",
            "        \"Task B Acc (Plasticity)\": acc_B_final,\n",
            "        \"Forgetting\": forgetting,\n",
            "        \"Zero-Shot A\": acc_A_zero,\n",
            "        \"Compression Damage\": compression_damage,\n",
            "        \"Forgetting (Training)\": acc_A_zero - acc_A_final,\n",
            "        \"Prep Time (s)\": prep_time\n",
            "    })\n",
            "    print(f\"Result {sp*100:.0f}%: Init A={acc_A_initial:.2f}%, Zero-Shot A={acc_A_zero:.2f}%, Final B={acc_B_final:.2f}%, Final A={acc_A_final:.2f}%\")\n"
        ]
    }

    updated_counts = 0
    # Use enumerate to modify in place
    for i, cell in enumerate(nb['cells']):
        source_str = "".join(cell.get('source', []))
        for key, new_source in updates.items():
            if key in source_str:
                nb['cells'][i]['source'] = new_source
                updated_counts += 1
                print(f"Updated cell: {key}")
                # We break the inner loop to avoid double matching, but continue outer loop
                break

    if updated_counts == len(updates):
        with open(nb_path, 'w', encoding='utf-8') as f:
            json.dump(nb, f, indent=4)
        print("All experiment cells updated successfully.")
    else:
        print(f"Warning: Only {updated_counts}/{len(updates)} cells were matched and updated.")
        
except Exception as e:
    print(f"Error: {e}")
